#pragma config(Sensor, in1,    leftLine,            sensorLineFollower)
#pragma config(Sensor, in2,    centerLine,          sensorLineFollower)
#pragma config(Sensor, in3,    rightLine,           sensorLineFollower)
#pragma config(Sensor, in4,    xAccel,              sensorAccelerometer)
#pragma config(Sensor, in5,    yAccel,              sensorAccelerometer)
#pragma config(Sensor, in6,    zAccel,              sensorAccelerometer)
#pragma config(Sensor, in7,    leftEncoder,         sensorQuadEncoder, int3)
#pragma config(Sensor, in8,    rightEncoder,        sensorQuadEncoder, int4)
#pragma config(Sensor, in9,    leftSonar,           sensorSONAR, int1)
#pragma config(Sensor, in10,   backSonar,           sensorSONAR, int2)
#pragma config(Sensor, in11,   rightSonar,          sensorSONAR, int1)
#pragma config(Motor,  port1,           driveLeft1,    tmotorNormal, openLoop)
#pragma config(Motor,  port2,           driveLeft2,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,           driveRight1,   tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port4,           driveRight2,   tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port5,           liftLeft1,     tmotorNormal, openLoop)
#pragma config(Motor,  port6,           liftLeft2,     tmotorNormal, openLoop)
#pragma config(Motor,  port7,           liftRight1,    tmotorNormal, openLoop)
#pragma config(Motor,  port8,           liftRight2,    tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(180)
#pragma userControlDuration(180)

/*   Justin Marple - V0.5    */
/* AI Implementations in PSC */
/*                           */
/*    Started  - 7/9/2012    */
/* Last Revision - 9/1/2012 */

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "GlobalVariables.c"//Contains all the variables in the code
#include "AutonomousControl/AutonomousControl.c"//Contains functions to move around the field autonomously
#include "PathGen/PathGen.c"//Contains Pathfinding code for finding paths using a Genetic Algorithm
#include "Motors/UpdateMotors.c"//Contains a loop for updating the motors
#include "Sensors/UpdateSensors.c"//Contains a loop for updating and filtering the sensors
#include "SeedConverter/SeedControl.c"//Contains code for converting a seed into an autonomous run
#include "UserControl/UserControl.c"//Contains code for human driving

void pre_auton()
{
  //Start generating a path
  StartTask(pathGen);

  //Start filtering/updating motors and sensors
  StartTask(updateSensors);
  StartTask(updateMotors);

  wait1Msec(5);//Let the sensors calibrate first
}

task autonomous()
{

}


task usercontrol()
{
  StartTask(ArcadeDriving);
}
